### ISSUE TITLE
Refactor `$to` (again) to use a dashboard system

### ISSUE THREAD

**Issue by LeptoSpira** [LeptoSpira/offthedialbot#59]
Attempt 2 trying to come up with a perfect tournament organizing system.

Use a dashboard (`$to`) and show a checklist of what's going on, what needs to be done, what has been completed, etc.

**Comment by DJam98** [comment]
Extend registration to occur during check in. If a player registers during check in they are automatically checked in

**Comment by LeptoSpira** [comment]
This may also extend to the signup command, allowing users to review their registration, and request things like a dropout

**Comment by LeptoSpira** [comment]
Let checkin persist after bot restart using a key in the database.
